### ISSUE TITLE
Cease and Desist

### ISSUE THREAD

**Issue by Derpthemeus** [Ponita0/YESuo#1]
Sieze Deez Nuts Request

No Yasuos allowed.

https://www.youtube.com/watch?v=2k0SmqbBIpQ

https://www.youtube.com/watch?v=9Deg7VrpHbM

Sincerely,
Derpthemeus
YasuNO LLC.
Head of Legal Team / Head of Illegal Team / Bird Lawyer

**Comment by geozukunft** [comment]
As the master of match-V5 I support this

**Comment by Ponita0** [comment]
Dear Derpthemeus:
    We've put your thoughts into consideration, but unfortunately According to what I have here
https://www.youtube.com/watch?v=dQw4w9WgXcQ
That's not possible at the moment. Thank you for reaching our lovely support.
With all respect.
Idk, no company's name yet

**Comment by Derpthemeus** [comment]
> That's not possible at the moment

Thanks for your quick response. Unfortunately, our records indicate otherwise. Please see the attached document. https://www.youtube.com/watch?v=Cgetjk9IHbo

**Comment by bangingheads** [comment]
As part of The People v. Ponita0, the following evidence has been filed under #69.

[https://www.youtube.com/watch?v=DTQfwMACjGA](https://www.youtube.com/watch?v=DTQfwMACjGA)

**Comment by Ponita0** [comment]
Dear Derpthemeus:
       Thank you for reaching our support again.
We've reviewed your order, and put into consideration your document.
But according to our data analysts:
![Alt 2](https://i.imgur.com/oUG9SbP.png)

Yasuo feeders are increasing recently, we would like to keep that going
We are doing great job
With all respect.
Idk, no company's name yet

**Comment by Ponita0** [comment]
> As part of The People v. Ponita0, the following evidence has been filed under #69.
> 
> https://www.youtube.com/watch?v=DTQfwMACjGA

That's how we work, more deaths = more success

**Comment by Derpthemeus** [comment]
Your data disagrees with a study we had conducted by an independent third-party. Please see attached
![1000_F_117695649_E4oQPZdHbGd0nZSFP2pyChJXj9ltuQUy](https://user-images.githubusercontent.com/16827162/161402814-d2e17eba-82d3-4cd6-bbc6-7936706ab29a.jpg)
.

**Comment by 5late** [comment]
I'd just like to interject for a moment. What you’re referring to as YESuo, is in fact, YESuo/YasuNO, or as I’ve recently taken to calling it, YESuo plus YasuNO. YESuo is not a program unto itself, but rather another free component of a fully functioning YasNO system made useful by the YasuNO corelibs, shell utilities and vital system components comprising a full shitpost as defined by Rito Games. Many computer users run a modified version of the YasuNO system every day, without realizing it. Through a peculiar turn of events, the version of YasuNO which is widely used today is often called “YESuo”, and many of its users are not aware that it is basically the YasuNO system, developed by the YasuNO Project. There really is a YESuo, and these people are using it, but it is just a part of the system they use. YESuo is the kernel: the program in the system that allocates the machine’s resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete shitpost. YESuo is normally used in combination with the YasuNO operating system: the whole system is basically YasuNO with YESuo added, or YasuNO/YESuo. All the so-called “YESuo” distributions are really distributions of YasuNO/YESuo.

Signed, 
~ Richard N Ballsman

**Comment by Ponita0** [comment]
Dear Richard N Ballsman:
       I hope you consider relooking at YESuo and maybe change your mind about it's being only part of YasuNO.
I totally disagree with this part, since YESuo can be a solution for yasuo lovers to defeat YasuoNO or any other upcoming Yasuo-preventing projects.
It's totally independent.
Our company - which doesn't have name yet- is preparing itself to face any future problems in yasuo-related field
Best wishes,
Our company - which doesn't have name yet -.

**Comment by Derpthemeus** [comment]
hey have you considered naming your company Stinky Feet Inc since you have stinky feet?

**Comment by Ponita0** [comment]
Thank you for your suggestion. We will put that into consideration due to lack of available names

**Comment by Derpthemeus** [comment]
Closing because Mr. Stinkyfeet beat me in a 1v1

**Comment by Derpthemeus** [comment]
but he was hacking for the record

**Comment by bangingheads** [comment]
Closing the issue will not close the lawsuit. We will see you in court.
